"""empty message

Revision ID: 7b68018390e6
Revises: 8021fd7bd66b
Create Date: 2020-11-07 01:10:58.431495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b68018390e6'
down_revision = '8021fd7bd66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'img_pro')
    op.drop_column('productos', 'precio')
    op.drop_column('productos', 'producto')
    op.drop_column('productos', 'descripcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('descripcion', sa.VARCHAR(length=100), nullable=True))
    op.add_column('productos', sa.Column('producto', sa.VARCHAR(length=35), nullable=False))
    op.add_column('productos', sa.Column('precio', sa.FLOAT(), nullable=False))
    op.add_column('productos', sa.Column('img_pro', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
