"""empty message

Revision ID: 8021fd7bd66b
Revises: 89502f74ad4f
Create Date: 2020-11-04 21:14:58.288878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8021fd7bd66b'
down_revision = '89502f74ad4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('img_pro', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'img_pro')
    # ### end Alembic commands ###
