"""empty message

Revision ID: b98597607349
Revises: 7b68018390e6
Create Date: 2020-11-10 00:47:47.411353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98597607349'
down_revision = '7b68018390e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrito',
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('valor_compra', sa.Float(), nullable=False),
    sa.Column('productos', sa.Float(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carrito')
    # ### end Alembic commands ###
